### ISSUE TITLE
Unable to get it working, fails saying `No such file or directory`

### ISSUE THREAD

**Issue by avinassh** [Baoyx007/tuntap-mac#1]
My code:

```rust
use tun_tap_mac as tun_tap;
use tun_tap_mac::Iface;

fn main() {
    let nic = Iface::new("utun0", tun_tap::Mode::Tun).expect("Failed to create a TUN device");
    // let name = iface.name();
// Configure the device ‒ set IP address on it, bring it up.
    let mut buffer = [0u8; 1504]; // MTU + 4 for the header
    let nbytes = nic.recv(&mut buffer).unwrap();
    eprintln!("got {} bytes: {:#?}", nbytes, &buffer[..nbytes])
}
```

and the full back trace:

```shell
thread 'main' panicked at 'Failed to create a TUN device: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:5:55
stack backtrace:
   0:        0x104a3a514 - std::backtrace_rs::backtrace::libunwind::trace::h3440e89bdeed3ddf
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x104a3a514 - std::backtrace_rs::backtrace::trace_unsynchronized::hfa68bcc7baf06ad7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104a3a514 - std::sys_common::backtrace::_print_fmt::h483e161a2ffbfba4
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x104a3a514 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h34f76b2ca42fab41
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x104a4da0d - core::fmt::write::h8f13d857463c51c1
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:        0x104a38406 - std::io::Write::write_fmt::h0a6214ccb1a8468b
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:        0x104a3c1c9 - std::sys_common::backtrace::_print::h7f3525175df798e8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x104a3c1c9 - std::sys_common::backtrace::print::hf68eec1a3c535c32
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x104a3c1c9 - std::panicking::default_hook::{{closure}}::hb14d90e928578cc7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:        0x104a3bd50 - std::panicking::default_hook::h460969f1dc8f738d
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:        0x104a3c84b - std::panicking::rust_panic_with_hook::h28bf9d6c3916221e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:        0x104a3c375 - std::panicking::begin_panic_handler::{{closure}}::h99569328be4adae9
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:        0x104a3a9b8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9a7e5cc6475b496b
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x104a3c2da - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:        0x104a532af - core::panicking::panic_fmt::h65997884a2662b8c
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:        0x104a531b5 - core::option::expect_none_failed::h5e793a721927d8b0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
  16:        0x104a17cf5 - core::result::Result<T,E>::expect::hbbdb7a24df9de4aa
                               at /Users/avi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933:23
  17:        0x104a1796e - trust::main::hd05c7980d91dcbb8
                               at /Users/avi/code/trust/src/main.rs:5:15
  18:        0x104a17ebe - core::ops::function::FnOnce::call_once::ha9527640c5fb89d4
                               at /Users/avi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  19:        0x104a17c61 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf002513cba3bdd23
                               at /Users/avi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  20:        0x104a17f54 - std::rt::lang_start::{{closure}}::h9d6bd5d15d748f9c
                               at /Users/avi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  21:        0x104a3cbc4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hde238ec10b1f717d
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
  22:        0x104a3cbc4 - std::panicking::try::do_call::h41236cf2e2b1c5e6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
  23:        0x104a3cbc4 - std::panicking::try::h0b8723b0a7df810a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
  24:        0x104a3cbc4 - std::panic::catch_unwind::heaaf12506fa6bab8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
  25:        0x104a3cbc4 - std::rt::lang_start_internal::h1faf79574185df6d
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
  26:        0x104a17f31 - std::rt::lang_start::h1537ab45089a7f8d
                               at /Users/avi/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  27:        0x104a17b92 - _main
```

**Comment by noreply-dev** [comment]
Same here :(

**Comment by noreplydev** [comment]
Same here :(, Something new after 2 years?
